// sync-engine/src/registry.rs
//
// TypeRegistry is the bridge between TOML config (string names like
// "UserTransform", "DbUser") and the actual Rust types generated by
// schema.toml.
//
// A business crate's main.rs registers its generated types once:
//
//   let mut reg = TypeRegistry::new();
//   reg.register_transform::<ApiUser, DbUser, UserTransform>("UserTransform");
//   reg.register_model::<DbUser>("DbUser");
//   reg.register_envelope::<ApiUserResponse>("ApiUserResponse");
//   sync_engine::run("pipeline.toml", reg).await
//
// The engine then uses the registry to instantiate the correct typed steps
// when it reads [[main_job.retry_steps]] entries from the TOML.

use anyhow::{anyhow, Result};
use std::any::Any;
use std::collections::HashMap;
use std::sync::Arc;

use crate::components::fetcher::HasEnvelope;
#[cfg(feature = "postgres")]
use crate::components::writer::UpsertableInTx;
use crate::context::JobContext;
use crate::pipeline::Transform;
use crate::step::Step;

// ── StepFactory ───────────────────────────────────────────────────────────

/// A factory that builds a concrete typed Step from config parameters.
pub trait StepFactory: Send + Sync {
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>>;

    /// Build a SpawnConsumerStep for this model type.
    fn build_consumer(
        &self,
        _queue:        &str,
        _commit_mode:  crate::step::consumer::CommitMode,
        _accum_slot:   Option<String>,
    ) -> Result<Box<dyn Step>> {
        Err(anyhow!("build_consumer not supported for this factory"))
    }

    /// Build an AutocommitUpsertStep (postgres strategy: autocommit).
    #[cfg(feature = "postgres")]
    fn build_autocommit(&self, _params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        Err(anyhow!("build_autocommit not supported for this factory"))
    }

    /// Build an EsIndexStep.
    #[cfg(feature = "elasticsearch")]
    fn build_es_index(
        &self,
        _reads: &str,
        _index: &str,
        _op:    crate::step::elasticsearch::EsOp,
    ) -> Result<Box<dyn Step>> {
        Err(anyhow!("build_es_index not supported for this factory"))
    }

    /// Build an EsFetchStep.
    #[cfg(feature = "elasticsearch")]
    fn build_es_fetch(
        &self,
        _writes:     &str,
        _index:      &str,
        _query:      Option<serde_json::Value>,
        _scroll_ttl: &str,
        _batch_size: i64,
        _append:     bool,
    ) -> Result<Box<dyn Step>> {
        Err(anyhow!("build_es_fetch not supported for this factory"))
    }

    /// Build a KafkaProduceStep.
    #[cfg(feature = "kafka")]
    fn build_kafka_produce(
        &self,
        _reads:     &str,
        _topic:     &str,
        _key_field: Option<String>,
    ) -> Result<Box<dyn Step>> {
        Err(anyhow!("build_kafka_produce not supported for this factory"))
    }

    /// Build a KafkaConsumeStep.
    #[cfg(feature = "kafka")]
    fn build_kafka_consume(
        &self,
        _writes:       &str,
        _topic:        &str,
        _max_messages: usize,
        _timeout_ms:   u64,
        _append:       bool,
    ) -> Result<Box<dyn Step>> {
        Err(anyhow!("build_kafka_consume not supported for this factory"))
    }
}

// ── TypeRegistry ──────────────────────────────────────────────────────────

#[derive(Default)]
pub struct TypeRegistry {
    transforms:  HashMap<String, Arc<dyn StepFactory>>,
    models:      HashMap<String, Arc<dyn StepFactory>>,
    queue_sends: HashMap<String, Arc<dyn StepFactory>>,
    envelopes:   HashMap<String, Arc<dyn StepFactory>>,
    post_hooks: HashMap<
        String,
        Arc<dyn Fn(Arc<JobContext>) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send>> + Send + Sync>,
    >,
}

impl TypeRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    // ── Registration ──────────────────────────────────────────────────────

    /// Register a generated Transform type by name.
    /// Builds a `TransformStep<Src, Dst, Xfm>` when the name appears in TOML.
    pub fn register_transform<Src, Dst, Xfm>(&mut self, name: &str)
    where
        Src: Any + Send + Sync + Clone + 'static,
        Dst: Any + Send + Sync + Clone + 'static,
        Xfm: Transform<Input = Src, Output = Dst> + Default + Send + Sync + 'static,
    {
        let factory = TransformFactory::<Src, Dst, Xfm> {
            _phantom: std::marker::PhantomData,
        };
        self.transforms
            .insert(name.to_owned(), Arc::new(factory));
    }

    /// Register a generated UpsertableInTx model type by name.
    /// Builds both a `TxUpsertStep<T>` and a `SendToQueueStep<T>` when the
    /// name appears in TOML — allowing the same model to be used in either
    /// the direct-commit (case 1/2) or producer/consumer (case 3/4) pattern.
    #[cfg(feature = "postgres")]
    pub fn register_model<T>(&mut self, name: &str)
    where
        T: UpsertableInTx + Any + Send + Sync + Clone + serde::Serialize + 'static,
    {
        let upsert_factory = ModelFactory::<T> { _phantom: std::marker::PhantomData };
        self.models.insert(name.to_owned(), Arc::new(upsert_factory));
        let queue_factory  = QueueSendFactory::<T> { _phantom: std::marker::PhantomData };
        self.queue_sends.insert(name.to_owned(), Arc::new(queue_factory));
    }

    /// Register a model that also implements `EsIndexable`.
    /// Supports both `es_index` / `es_fetch` steps AND `tx_upsert` / `spawn_consumer`.
    /// Use this instead of `register_model` when the model is written to Elasticsearch.
    #[cfg(all(feature = "elasticsearch", feature = "postgres"))]
    pub fn register_model_es<T>(&mut self, name: &str)
    where
        T: crate::step::elasticsearch::EsIndexable
            + UpsertableInTx
            + serde::de::DeserializeOwned
            + Any + Send + Sync + Clone + serde::Serialize + 'static,
    {
        let factory = Arc::new(EsModelFactory::<T> { _phantom: std::marker::PhantomData });
        self.models.insert(name.to_owned(), Arc::clone(&factory) as Arc<dyn StepFactory>);
        let queue_factory = QueueSendFactory::<T> { _phantom: std::marker::PhantomData };
        self.queue_sends.insert(name.to_owned(), Arc::new(queue_factory));
    }

    /// Register a generated HasEnvelope type by name.
    /// Builds a `FetchJsonStep<Env>` when the name appears in TOML.
    pub fn register_envelope<Env>(&mut self, name: &str)
    where
        Env: HasEnvelope + serde::de::DeserializeOwned + Send + Sync + 'static,
        Env::Item: Any + Send + Sync + Clone + 'static,
    {
        let factory = EnvelopeFactory::<Env> {
            _phantom: std::marker::PhantomData,
        };
        self.envelopes.insert(name.to_owned(), Arc::new(factory));
    }

    /// Register a custom post-job hook by name.
    pub fn register_post_hook<F, Fut>(&mut self, name: &str, f: F)
    where
        F: Fn(Arc<JobContext>) -> Fut + Send + Sync + 'static,
        Fut: std::future::Future<Output = Result<()>> + Send + 'static,
    {
        self.post_hooks.insert(
            name.to_owned(),
            Arc::new(move |ctx| Box::pin(f(ctx))),
        );
    }

    // ── Lookup ────────────────────────────────────────────────────────────

    pub fn build_transform(
        &self,
        name: &str,
        params: &HashMap<String, String>,
    ) -> Result<Box<dyn Step>> {
        self.transforms
            .get(name)
            .ok_or_else(|| anyhow!("Transform \"{name}\" not registered — call registry.register_transform::<Src, Dst, {name}>(\"{name}\") in main.rs"))?
            .build(params)
    }

    #[cfg(feature = "postgres")]
    pub fn build_model_sink(&self, name: &str, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        self.models.get(name)
            .ok_or_else(|| anyhow!("Model \"{name}\" not registered — add registry.register_model::<{name}>(\"{name}\") in main.rs"))?
            .build(params)
    }

    #[cfg(feature = "postgres")]
    pub fn build_consumer(
        &self, model: &str, queue: &str,
        commit_mode: crate::step::consumer::CommitMode,
        accum_slot:  Option<String>,
    ) -> Result<Box<dyn Step>> {
        self.models.get(model)
            .ok_or_else(|| anyhow!("Model \"{model}\" not registered — add registry.register_model::<{model}>(\"{model}\") in main.rs"))?
            .build_consumer(queue, commit_mode, accum_slot)
    }

    pub fn build_queue_send(&self, name: &str, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        self.queue_sends.get(name)
            .ok_or_else(|| anyhow!("Model \"{name}\" not registered for queue send — add registry.register_model::<{name}>(\"{name}\") in main.rs"))?
            .build(params)
    }

    pub fn build_fetch(&self, name: &str, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        self.envelopes
            .get(name)
            .ok_or_else(|| anyhow!("Envelope \"{name}\" not registered — call registry.register_envelope::<{name}>(\"{name}\") in main.rs"))?
            .build(params)
    }

    /// Build an AutocommitUpsertStep (postgres strategy: autocommit).
    #[cfg(feature = "postgres")]
    pub fn build_autocommit_sink(&self, name: &str, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        self.models.get(name)
            .ok_or_else(|| anyhow!("Model \"{name}\" not registered — add registry.register_model::<{name}>(\"{name}\") in main.rs"))?
            .build_autocommit(params)
    }

    /// Build an EsIndexStep for the given model.
    #[cfg(feature = "elasticsearch")]
    pub fn build_es_index(
        &self,
        name:  &str,
        reads: &str,
        index: &str,
        op:    crate::step::elasticsearch::EsOp,
    ) -> Result<Box<dyn Step>> {
        self.models.get(name)
            .or_else(|| self.envelopes.get(name))
            .ok_or_else(|| anyhow!("Model/envelope \"{name}\" not registered"))?
            .build_es_index(reads, index, op)
    }

    /// Build an EsFetchStep for the given model.
    #[cfg(feature = "elasticsearch")]
    pub fn build_es_fetch(
        &self,
        name:       &str,
        writes:     &str,
        index:      &str,
        query:      Option<serde_json::Value>,
        scroll_ttl: &str,
        batch_size: i64,
        append:     bool,
    ) -> Result<Box<dyn Step>> {
        self.envelopes.get(name)
            .or_else(|| self.models.get(name))
            .ok_or_else(|| anyhow!("Model/envelope \"{name}\" not registered"))?
            .build_es_fetch(writes, index, query, scroll_ttl, batch_size, append)
    }

    /// Build a KafkaProduceStep for the given model.
    #[cfg(feature = "kafka")]
    pub fn build_kafka_produce(
        &self,
        name:      &str,
        reads:     &str,
        topic:     &str,
        key_field: Option<String>,
    ) -> Result<Box<dyn Step>> {
        self.models.get(name)
            .ok_or_else(|| anyhow!("Model \"{name}\" not registered"))?
            .build_kafka_produce(reads, topic, key_field)
    }

    /// Build a KafkaConsumeStep for the given model.
    #[cfg(feature = "kafka")]
    pub fn build_kafka_consume(
        &self,
        name:         &str,
        writes:       &str,
        topic:        &str,
        max_messages: usize,
        timeout_ms:   u64,
        append:       bool,
    ) -> Result<Box<dyn Step>> {
        self.envelopes.get(name)
            .or_else(|| self.models.get(name))
            .ok_or_else(|| anyhow!("Model/envelope \"{name}\" not registered"))?
            .build_kafka_consume(writes, topic, max_messages, timeout_ms, append)
    }

    pub fn get_post_hook(
        &self,
        name: &str,
    ) -> Option<Arc<dyn Fn(Arc<JobContext>) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send>> + Send + Sync>> {
        self.post_hooks.get(name).cloned()
    }

    // ── Validation helpers ────────────────────────────────────────────────
    pub fn has_transform(&self,  name: &str) -> bool { self.transforms.contains_key(name) }
    #[cfg(feature = "postgres")]
    pub fn has_model(&self,      name: &str) -> bool { self.models.contains_key(name) }
    pub fn has_queue_send(&self, name: &str) -> bool { self.queue_sends.contains_key(name) }
    pub fn has_envelope(&self,   name: &str) -> bool { self.envelopes.contains_key(name) }
}

// ── Concrete factories ────────────────────────────────────────────────────

struct TransformFactory<Src, Dst, Xfm> {
    _phantom: std::marker::PhantomData<(Src, Dst, Xfm)>,
}

impl<Src, Dst, Xfm> StepFactory for TransformFactory<Src, Dst, Xfm>
where
    Src: Any + Send + Sync + Clone + 'static,
    Dst: Any + Send + Sync + Clone + 'static,
    Xfm: Transform<Input = Src, Output = Dst> + Default + Send + Sync + 'static,
{
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        let reads  = params.get("reads").cloned().unwrap_or_else(|| "api_rows".into());
        let writes = params.get("writes").cloned().unwrap_or_else(|| "db_rows".into());
        let append = params.get("append").map(|v| v == "true").unwrap_or(false);
        Ok(Box::new(crate::step::transform::TransformStep::<Src, Dst, Xfm>::new(
            reads, writes, append, Xfm::default(),
        )))
    }
}

#[cfg(feature = "postgres")]
struct ModelFactory<T> {
    _phantom: std::marker::PhantomData<T>,
}

#[cfg(feature = "postgres")]
impl<T> StepFactory for ModelFactory<T>
where
    T: UpsertableInTx + Any + Send + Sync + Clone + serde::Serialize + 'static,
{
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        let reads = params.get("reads").cloned().unwrap_or_else(|| "db_rows".into());
        Ok(Box::new(crate::step::sink::TxUpsertStep::<T>::new(reads)))
    }

    fn build_consumer(
        &self, queue: &str,
        commit_mode: crate::step::consumer::CommitMode,
        accum_slot:  Option<String>,
    ) -> Result<Box<dyn Step>> {
        use crate::step::consumer::{CommitMode, SpawnConsumerStep};
        Ok(match commit_mode {
            CommitMode::PerBatch =>
                Box::new(SpawnConsumerStep::<T>::per_batch(queue)),
            CommitMode::DrainInPostJob =>
                Box::new(SpawnConsumerStep::<T>::drain_in_post_job(
                    queue,
                    accum_slot.unwrap_or_else(|| format!("__accum_{queue}")),
                )),
        })
    }

    #[cfg(feature = "postgres")]
    fn build_autocommit(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        // AutocommitUpsertStep uses UpsertableInTx (one tx per row) — no extra trait needed.
        let reads = params.get("reads").cloned().unwrap_or_else(|| "db_rows".into());
        Ok(Box::new(crate::step::autocommit::AutocommitUpsertStep::<T>::new(reads)))
    }

    #[cfg(feature = "elasticsearch")]
    fn build_es_index(
        &self,
        reads: &str,
        index: &str,
        op:    crate::step::elasticsearch::EsOp,
    ) -> Result<Box<dyn Step>>
    where
    {
        use crate::step::elasticsearch::{EsIndexable, EsIndexStep};
        // T must implement EsIndexable — enforced via register_model_es.
        // We use a blanket approach: build the step and let the type checker validate.
        struct Wrapper<U>(std::marker::PhantomData<U>);
        // The step is generic over T; we just need T: EsIndexable here.
        // Since ModelFactory<T> already requires T: Serialize + Send + Sync,
        // and EsIndexable requires the same + es_id(), we cast via the trait.
        Err(anyhow!(
            "es_index on a model requires T to implement EsIndexable. \
             Use registry.register_model_es::<T>(name) instead of register_model."
        ))
    }

    #[cfg(feature = "kafka")]
    fn build_kafka_produce(
        &self,
        reads:     &str,
        topic:     &str,
        key_field: Option<String>,
    ) -> Result<Box<dyn Step>> {
        use crate::step::kafka::KafkaProduceStep;
        Ok(Box::new(KafkaProduceStep::<T>::new(reads, topic, key_field)))
    }
}

/// Builds a transport-aware queue send step.
/// At runtime the step checks whether __rmq_queue_{name} is set in context;
/// if so it uses RabbitmqSendStep, otherwise SendToQueueStep (tokio mpsc).
struct QueueSendFactory<T> {
    _phantom: std::marker::PhantomData<fn() -> T>,
}

impl<T> StepFactory for QueueSendFactory<T>
where
    T: Any + Send + Sync + Clone + serde::Serialize + 'static,
{
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        let reads = params.get("reads").cloned().unwrap_or_else(|| "db_rows".into());
        let queue = params.get("queue").cloned().unwrap_or_else(|| "db_rows".into());
        Ok(Box::new(AutoQueueSendStep::<T> {
            reads,
            queue,
            _phantom: std::marker::PhantomData,
        }))
    }
}

/// Dispatches to RabbitmqSendStep or SendToQueueStep based on context at runtime.
struct AutoQueueSendStep<T> {
    reads: String,
    queue: String,
    _phantom: std::marker::PhantomData<fn() -> T>,
}

#[async_trait::async_trait]
impl<T> Step for AutoQueueSendStep<T>
where
    T: Any + Send + Sync + Clone + serde::Serialize + 'static,
{
    fn name(&self) -> &str { "send_to_queue" }

    async fn run(&self, ctx: &crate::context::JobContext) -> anyhow::Result<()> {
        let rmq_slot = format!("__rmq_queue_{}", self.queue);
        if ctx.slot_is_set(&rmq_slot).await {
            // RabbitMQ path
            crate::step::queue_send::RabbitmqSendStep::<T>::new(
                &self.reads, &self.queue,
            )
            .run(ctx)
            .await
        } else {
            // Tokio mpsc path
            crate::step::sink::SendToQueueStep::<T>::new(
                &self.reads, &self.queue,
            )
            .run(ctx)
            .await
        }
    }
}

struct EnvelopeFactory<Env> {
    _phantom: std::marker::PhantomData<Env>,
}

impl<Env> StepFactory for EnvelopeFactory<Env>
where
    Env: HasEnvelope + serde::de::DeserializeOwned + Send + Sync + 'static,
    Env::Item: Any + Send + Sync + Clone + 'static,
{
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        let writes = params.get("writes").cloned().unwrap_or_else(|| "api_rows".into());
        let append = params.get("append").map(|v| v == "true").unwrap_or(false);
        Ok(Box::new(crate::step::fetch::FetchJsonStep::<Env>::new(writes, append)))
    }

    #[cfg(feature = "elasticsearch")]
    fn build_es_fetch(
        &self,
        writes:     &str,
        index:      &str,
        query:      Option<serde_json::Value>,
        scroll_ttl: &str,
        batch_size: i64,
        append:     bool,
    ) -> Result<Box<dyn Step>> {
        use crate::step::elasticsearch::EsFetchStep;
        Ok(Box::new(EsFetchStep::<Env::Item>::new(
            writes, index, query, scroll_ttl, batch_size, append,
        )))
    }

    #[cfg(feature = "kafka")]
    fn build_kafka_consume(
        &self,
        writes:       &str,
        topic:        &str,
        max_messages: usize,
        timeout_ms:   u64,
        append:       bool,
    ) -> Result<Box<dyn Step>> {
        use crate::step::kafka::KafkaConsumeStep;
        Ok(Box::new(KafkaConsumeStep::<Env::Item>::new(
            writes, topic, max_messages, timeout_ms, append,
        )))
    }
}

// ── EsModelFactory — for T: EsIndexable ──────────────────────────────────
//
// Used by register_model_es. Supports both es_index (sink) and postgres
// tx_upsert (via UpsertableInTx), so a model can be written to both.

#[cfg(feature = "elasticsearch")]
struct EsModelFactory<T> {
    _phantom: std::marker::PhantomData<T>,
}

#[cfg(all(feature = "elasticsearch", feature = "postgres"))]
impl<T> StepFactory for EsModelFactory<T>
where
    T: crate::step::elasticsearch::EsIndexable
        + UpsertableInTx
        + serde::de::DeserializeOwned
        + Any + Send + Sync + Clone + 'static,
{
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        let reads = params.get("reads").cloned().unwrap_or_else(|| "db_rows".into());
        Ok(Box::new(crate::step::sink::TxUpsertStep::<T>::new(reads)))
    }

    fn build_es_index(
        &self,
        reads: &str,
        index: &str,
        op:    crate::step::elasticsearch::EsOp,
    ) -> Result<Box<dyn Step>> {
        use crate::step::elasticsearch::EsIndexStep;
        Ok(Box::new(EsIndexStep::<T>::new(reads, index, op)))
    }

    fn build_es_fetch(
        &self,
        writes:     &str,
        index:      &str,
        query:      Option<serde_json::Value>,
        scroll_ttl: &str,
        batch_size: i64,
        append:     bool,
    ) -> Result<Box<dyn Step>> {
        use crate::step::elasticsearch::EsFetchStep;
        Ok(Box::new(EsFetchStep::<T>::new(
            writes, index, query, scroll_ttl, batch_size, append,
        )))
    }

    fn build_consumer(
        &self,
        queue: &str,
        commit_mode: crate::step::consumer::CommitMode,
        accum_slot:  Option<String>,
    ) -> Result<Box<dyn Step>> {
        use crate::step::consumer::{CommitMode, SpawnConsumerStep};
        Ok(match commit_mode {
            CommitMode::PerBatch =>
                Box::new(SpawnConsumerStep::<T>::per_batch(queue)),
            CommitMode::DrainInPostJob =>
                Box::new(SpawnConsumerStep::<T>::drain_in_post_job(
                    queue,
                    accum_slot.unwrap_or_else(|| format!("__accum_{queue}")),
                )),
        })
    }
}
