// sync-engine/src/registry.rs
//
// TypeRegistry is the bridge between TOML config (string names like
// "UserTransform", "DbUser") and the actual Rust types generated by
// schema.toml.
//
// A business crate's main.rs registers its generated types once:
//
//   let mut reg = TypeRegistry::new();
//   reg.register_transform::<ApiUser, DbUser, UserTransform>("UserTransform");
//   reg.register_model::<DbUser>("DbUser");
//   reg.register_envelope::<ApiUserResponse>("ApiUserResponse");
//   sync_engine::run("pipeline.toml", reg).await
//
// The engine then uses the registry to instantiate the correct typed steps
// when it reads [[main_job.retry_steps]] entries from the TOML.

use anyhow::{anyhow, Result};
use std::any::Any;
use std::collections::HashMap;
use std::sync::Arc;

use crate::components::fetcher::HasEnvelope;
use crate::components::writer::UpsertableInTx;
use crate::context::JobContext;
use crate::pipeline::Transform;
use crate::step::Step;

// ── Erased step factory ───────────────────────────────────────────────────

/// A factory that builds a concrete typed Step from config parameters.
/// The engine calls this when assembling the step runner from TOML.
pub trait StepFactory: Send + Sync {
    /// Build a step given the config map for this step entry.
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>>;
}

// ── TypeRegistry ──────────────────────────────────────────────────────────

#[derive(Default)]
pub struct TypeRegistry {
    /// Named transform factories: "UserTransform" → factory
    transforms: HashMap<String, Arc<dyn StepFactory>>,
    /// Named model upsert factories: "DbUser" → factory that builds TxUpsertStep
    models: HashMap<String, Arc<dyn StepFactory>>,
    /// Named envelope fetch factories: "ApiUserResponse" → factory that builds FetchJsonStep
    envelopes: HashMap<String, Arc<dyn StepFactory>>,
    /// Named custom post-job hooks
    post_hooks: HashMap<
        String,
        Arc<
            dyn Fn(
                    Arc<JobContext>,
                )
                    -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send>>
                + Send
                + Sync,
        >,
    >,
}

impl TypeRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    // ── Registration ──────────────────────────────────────────────────────

    /// Register a generated Transform type by name.
    /// Builds a `TransformStep<Src, Dst, Xfm>` when the name appears in TOML.
    pub fn register_transform<Src, Dst, Xfm>(&mut self, name: &str)
    where
        Src: Any + Send + Sync + Clone + 'static,
        Dst: Any + Send + Sync + Clone + 'static,
        Xfm: Transform<Input = Src, Output = Dst> + Default + Send + Sync + 'static,
    {
        let factory = TransformFactory::<Src, Dst, Xfm> {
            _phantom: std::marker::PhantomData,
        };
        self.transforms.insert(name.to_owned(), Arc::new(factory));
    }

    /// Register a generated UpsertableInTx model type by name.
    /// Builds a `TxUpsertStep<T>` when the name appears in TOML.
    pub fn register_model<T>(&mut self, name: &str)
    where
        T: UpsertableInTx + Any + Send + Sync + Clone + 'static,
    {
        let factory = ModelFactory::<T> {
            _phantom: std::marker::PhantomData,
        };
        self.models.insert(name.to_owned(), Arc::new(factory));
    }

    /// Register a generated HasEnvelope type by name.
    /// Builds a `FetchJsonStep<Env>` when the name appears in TOML.
    pub fn register_envelope<Env>(&mut self, name: &str)
    where
        Env: HasEnvelope + serde::de::DeserializeOwned + Send + Sync + 'static,
        Env::Item: Any + Send + Sync + Clone + 'static,
    {
        let factory = EnvelopeFactory::<Env> {
            _phantom: std::marker::PhantomData,
        };
        self.envelopes.insert(name.to_owned(), Arc::new(factory));
    }

    /// Register a custom post-job hook by name.
    pub fn register_post_hook<F, Fut>(&mut self, name: &str, f: F)
    where
        F: Fn(Arc<JobContext>) -> Fut + Send + Sync + 'static,
        Fut: std::future::Future<Output = Result<()>> + Send + 'static,
    {
        self.post_hooks
            .insert(name.to_owned(), Arc::new(move |ctx| Box::pin(f(ctx))));
    }

    // ── Lookup ────────────────────────────────────────────────────────────

    pub fn build_transform(
        &self,
        name: &str,
        params: &HashMap<String, String>,
    ) -> Result<Box<dyn Step>> {
        self.transforms
            .get(name)
            .ok_or_else(|| anyhow!("Transform \"{name}\" not registered — call registry.register_transform::<Src, Dst, {name}>(\"{name}\") in main.rs"))?
            .build(params)
    }

    pub fn build_model_sink(
        &self,
        name: &str,
        params: &HashMap<String, String>,
    ) -> Result<Box<dyn Step>> {
        self.models
            .get(name)
            .ok_or_else(|| anyhow!("Model \"{name}\" not registered — call registry.register_model::<{name}>(\"{name}\") in main.rs"))?
            .build(params)
    }

    pub fn build_fetch(
        &self,
        name: &str,
        params: &HashMap<String, String>,
    ) -> Result<Box<dyn Step>> {
        self.envelopes
            .get(name)
            .ok_or_else(|| anyhow!("Envelope \"{name}\" not registered — call registry.register_envelope::<{name}>(\"{name}\") in main.rs"))?
            .build(params)
    }

    pub fn get_post_hook(
        &self,
        name: &str,
    ) -> Option<
        Arc<
            dyn Fn(
                    Arc<JobContext>,
                )
                    -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send>>
                + Send
                + Sync,
        >,
    > {
        self.post_hooks.get(name).cloned()
    }
}

// ── Concrete factories ────────────────────────────────────────────────────

struct TransformFactory<Src, Dst, Xfm> {
    _phantom: std::marker::PhantomData<(Src, Dst, Xfm)>,
}

impl<Src, Dst, Xfm> StepFactory for TransformFactory<Src, Dst, Xfm>
where
    Src: Any + Send + Sync + Clone + 'static,
    Dst: Any + Send + Sync + Clone + 'static,
    Xfm: Transform<Input = Src, Output = Dst> + Default + Send + Sync + 'static,
{
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        let reads = params
            .get("reads")
            .cloned()
            .unwrap_or_else(|| "api_rows".into());
        let writes = params
            .get("writes")
            .cloned()
            .unwrap_or_else(|| "db_rows".into());
        let append = params.get("append").map(|v| v == "true").unwrap_or(false);
        Ok(Box::new(crate::step::transform::TransformStep::<
            Src,
            Dst,
            Xfm,
        >::new(
            reads, writes, append, Xfm::default()
        )))
    }
}

struct ModelFactory<T> {
    _phantom: std::marker::PhantomData<T>,
}

impl<T> StepFactory for ModelFactory<T>
where
    T: UpsertableInTx + Any + Send + Sync + Clone + 'static,
{
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        let reads = params
            .get("reads")
            .cloned()
            .unwrap_or_else(|| "db_rows".into());
        Ok(Box::new(crate::step::sink::TxUpsertStep::<T>::new(reads)))
    }
}

struct EnvelopeFactory<Env> {
    _phantom: std::marker::PhantomData<Env>,
}

impl<Env> StepFactory for EnvelopeFactory<Env>
where
    Env: HasEnvelope + serde::de::DeserializeOwned + Send + Sync + 'static,
    Env::Item: Any + Send + Sync + Clone + 'static,
{
    fn build(&self, params: &HashMap<String, String>) -> Result<Box<dyn Step>> {
        let writes = params
            .get("writes")
            .cloned()
            .unwrap_or_else(|| "api_rows".into());
        let append = params.get("append").map(|v| v == "true").unwrap_or(false);
        Ok(Box::new(crate::step::fetch::FetchJsonStep::<Env>::new(
            writes, append,
        )))
    }
}
