// sync-engine/src/components/writer.rs — requires feature "postgres"
#![cfg(feature = "postgres")]
use anyhow::Result;
use async_trait::async_trait;
use sqlx::{postgres::PgPoolOptions, PgPool};
use tracing::{error, info, warn};

use crate::pipeline::component_registry::{AnyPostHook, AnyWriter};
use crate::pipeline::Sink;

// ── Upsertable (pool) ─────────────────────────────────────────────────────

/// Implemented by generated record types via `build.rs` → `upserts.rs`.
/// Used by `PostgresWriter` for non-transactional batch writes.
#[async_trait]
pub trait Upsertable: Send + Sync + 'static {
    async fn upsert(&self, pool: &sqlx::PgPool) -> Result<()>;
}

// ── UpsertableInTx (transaction) ──────────────────────────────────────────

/// Also generated by `build.rs` → `upserts.rs` (when `sink.upsert = true`).
/// Used by `TxWriter` so an entire window is committed atomically.
#[async_trait]
pub trait UpsertableInTx: Send + Sync + 'static {
    async fn upsert_in_tx(&self, tx: &mut sqlx::Transaction<'_, sqlx::Postgres>) -> Result<()>;
}

// ── PostgresWriter (pool-based) ───────────────────────────────────────────

pub struct PostgresWriter<T> {
    pool:     PgPool,
    _phantom: std::marker::PhantomData<T>,
}

impl<T: Upsertable> PostgresWriter<T> {
    pub async fn new(database_url: &str) -> Result<Self> {
        let pool = PgPoolOptions::new()
            .max_connections(5)
            .connect(database_url)
            .await?;
        Ok(Self { pool, _phantom: std::marker::PhantomData })
    }
}

#[async_trait]
impl<T: Upsertable> Sink for PostgresWriter<T> {
    type Item = T;
    async fn write(&self, items: Vec<T>) {
        info!("Writing {} records", items.len());
        for item in items {
            if let Err(e) = item.upsert(&self.pool).await {
                error!(error = %e, "Upsert failed — skipping row");
            }
        }
    }
}

// ── TxWriter (transactional) ──────────────────────────────────────────────

/// Writes an entire batch inside a single Postgres transaction.
/// On any upsert error the row is skipped; the rest of the batch still commits.
pub struct TxWriter<T> {
    pub pool: PgPool,
    _phantom: std::marker::PhantomData<T>,
}

impl<T: UpsertableInTx> TxWriter<T> {
    pub fn new(pool: PgPool) -> Self {
        Self { pool, _phantom: std::marker::PhantomData }
    }

    pub async fn write_batch(&self, items: &[T]) -> Result<(usize, usize)> {
        let mut tx       = self.pool.begin().await?;
        let mut upserted = 0usize;
        let mut skipped  = 0usize;
        for item in items {
            match item.upsert_in_tx(&mut tx).await {
                Ok(_)  => upserted += 1,
                Err(e) => {
                    error!(error = %e, "Upsert skipped");
                    skipped += 1;
                }
            }
        }
        tx.commit().await?;
        info!(upserted, skipped, "Batch committed");
        Ok((upserted, skipped))
    }
}

// ── WriterAdapter (type-erased AnyWriter for the dynamic pipeline) ────────

pub struct WriterAdapter<T>(pub PostgresWriter<T>);

#[async_trait]
impl<T: Upsertable> AnyWriter for WriterAdapter<T> {
    async fn write_erased(&self, items: Vec<Box<dyn std::any::Any + Send>>) {
        let typed: Vec<T> = items
            .into_iter()
            .filter_map(|b| b.downcast::<T>().ok().map(|v| *v))
            .collect();
        self.0.write(typed).await;
    }
}

// ── Post-hooks ────────────────────────────────────────────────────────────

pub struct RawSqlHook {
    pub pool: PgPool,
    pub sql:  String,
}

impl RawSqlHook {
    pub fn new(pool: PgPool, sql: String) -> Self {
        Self { pool, sql }
    }
}

#[async_trait]
impl AnyPostHook for RawSqlHook {
    async fn on_complete(&self) {
        info!("Running post-sync SQL");
        if let Err(e) = sqlx::raw_sql(&self.sql).execute(&self.pool).await {
            warn!(error = %e, "Post-sync SQL failed");
        }
    }
}

pub struct NoopHook;

#[async_trait]
impl AnyPostHook for NoopHook {
    async fn on_complete(&self) {}
}
